-- DISTINCT로 중복 제거
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
  ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단'
  AND MONTH(H.START_DATE) = 10 -- MONTH로 DATETIME에서 월만 추출
ORDER BY C.CAR_ID DESC;