SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS "TOTAL_ORDER"
FROM FIRST_HALF AS FH INNER JOIN ICECREAM_INFO AS II
ON FH.FLAVOR = II.FLAVOR -- JOIN 조건 추가 (ON 없으면 카타시안 곱)
GROUP BY II.INGREDIENT_TYPE
ORDER BY SUM(TOTAL_ORDER) ASC;