SELECT CAR_TYPE, COUNT(CAR_TYPE) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;

--

SELECT 
    CAR_TYPE,
    COUNT(*) AS CARS
FROM 
    CAR_RENTAL_COMPANY_CAR
WHERE 
    -- 정규표현식(|: OR 연산자)을 사용해 세 키워드 중 하나라도 포함된 데이터 필터링
    OPTIONS REGEXP '통풍시트|열선시트|가죽시트'
GROUP BY 
    CAR_TYPE
ORDER BY 
    CAR_TYPE ASC;