SELECT
    CAR_ID,
    -- ROUND 함수를 통해 1자리까지 (2번째 자리에서) 반올림
    -- 대여기간이 같은 경우 1이 되어야 하기에 +1
    -- DATEDIFF 함수를 통해 두 일자의 차이 구하기
    ROUND(AVG(DATEDIFF (END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;