WITH ORDER_LIST AS (
    SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
    FROM FOOD_PRODUCT FP JOIN  FOOD_ORDER FO
    ON FP.PRODUCT_ID = FO.PRODUCT_ID
    WHERE FO.PRODUCE_DATE >= '2022-05-01'
        AND FO.PRODUCE_DATE < '2022-06-01'
)
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM ORDER_LIST
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;