WITH REVIEW_CNT AS (
    SELECT MP.MEMBER_ID, COUNT(RR.REVIEW_ID) AS CNT
    FROM MEMBER_PROFILE MP JOIN REST_REVIEW RR
        ON MP.MEMBER_ID = RR.MEMBER_ID
    GROUP BY MP.MEMBER_ID
),
MAX_CNT AS (
    SELECT MAX(CNT) AS MAX_VAL
    FROM REVIEW_CNT
),
MAX_IDS AS (
    SELECT MEMBER_ID
    FROM REVIEW_CNT
    WHERE CNT = (
        SELECT MAX_VAL
        FROM MAX_CNT
    )
)
SELECT MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP JOIN REST_REVIEW RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_IDS)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;