WITH JOINED_DATA AS (
    SELECT UI.USER_ID, GENDER, AGE, JOINED, ONLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM USER_INFO UI INNER JOIN ONLINE_SALE OS
        ON UI.USER_ID = OS.USER_ID
    WHERE UI.GENDER IS NOT NULL
)
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    -- DISTINCT로 USER_ID에 대한 중복 제거 필요
    COUNT(DISTINCT USER_ID) AS USERS
FROM JOINED_DATA
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC, GENDER ASC;