WITH RANKED AS (
    SELECT
        ID,
        -- ROW_NUMBER() > OVER () > PARTITION BY > ORDER BY
        ROW_NUMBER() OVER (
            ORDER BY SIZE_OF_COLONY DESC
        ) AS RN
    FROM ECOLI_DATA
)
SELECT
    ID,
    CASE
        WHEN RN <= ((SELECT MAX(RN) FROM RANKED) * 0.25) THEN 'CRITICAL'
        WHEN RN <= ((SELECT MAX(RN) FROM RANKED) * 0.50) THEN 'HIGH'
        WHEN RN <= ((SELECT MAX(RN) FROM RANKED) * 0.75) THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM RANKED
ORDER BY ID;