WITH MAX_LEN AS (
    SELECT
        ID,
        FISH_TYPE,
        MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
),
MAX_FISH AS (
    SELECT
        FI.ID,
        FI.FISH_TYPE,
        FI.LENGTH
    -- JOIN의 조건을 FISH_TYPE까지 함께 주어서
    -- FISH_TYPE별 최댓값인 물고기의 ID 추출
    FROM FISH_INFO FI JOIN MAX_LEN ML
        ON FI.FISH_TYPE = ML.FISH_TYPE
        AND FI.LENGTH = ML.LENGTH
)
SELECT
    MF.ID,
    FNI.FISH_NAME,
    MF.LENGTH
FROM MAX_FISH MF JOIN FISH_NAME_INFO FNI
    ON MF.FISH_TYPE = FNI.FISH_TYPE
ORDER BY MF.ID ASC;