WITH NORM_USER AS (
    SELECT USER_ID, JOINED
    FROM USER_INFO
    WHERE JOINED >= '2021-01-01'
        AND JOINED < '2022-01-01'
)
SELECT
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(USER_ID) FROM NORM_USER), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS INNER JOIN NORM_USER NU
    ON OS.USER_ID = NU.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;