WITH SEOUL_REST AS (
    SELECT REST_ID
    FROM REST_INFO
    WHERE ADDRESS LIKE "서울%"
)
SELECT
    RI.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO RI JOIN REST_REVIEW RR
    ON RI.REST_ID = RR.REST_ID
WHERE RI.REST_ID IN (SELECT REST_ID FROM SEOUL_REST)
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;