WITH UP AS (
    SELECT
        DISTINCT II.ITEM_ID
    FROM ITEM_INFO II JOIN ITEM_TREE IT
        ON II.ITEM_ID = IT.PARENT_ITEM_ID
)
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (SELECT * FROM UP)
ORDER BY ITEM_ID DESC;