WITH YEAR_MAX AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
)
SELECT
    YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    (YM.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV,
    ED.ID
FROM ECOLI_DATA ED JOIN YEAR_MAX YM
    ON YEAR(ED.DIFFERENTIATION_DATE) = YM.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;