WITH UNION_DATE AS ( 
    SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE 
    FROM ONLINE_SALE 
    WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01' 
    
    UNION ALL 
    -- NULL AS 컬럼명으로 NULL값으로 대체
    SELECT NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE 
    FROM OFFLINE_SALE 
    WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01' 
) 
SELECT 
    -- 날짜 포맷 변경
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
    PRODUCT_ID, 
    -- IFNULL 제거 (실제 NULL 값으로 출력)
    USER_ID,
    SALES_AMOUNT 
FROM UNION_DATE 
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;