WITH BOOK_AUTHOR AS (
    SELECT
        AUTHOR.AUTHOR_ID,
        AUTHOR.AUTHOR_NAME,
        BOOK.BOOK_ID,
        BOOK.CATEGORY,
        BOOK.PRICE
    FROM BOOK JOIN AUTHOR
        ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
)
SELECT
    BA.AUTHOR_ID,
    BA.AUTHOR_NAME,
    BA.CATEGORY,
    SUM(BS.SALES * BA.PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS JOIN BOOK_AUTHOR BA
    ON BS.BOOK_ID = BA.BOOK_ID
WHERE BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE < '2022-02-01'
GROUP BY BA.AUTHOR_ID, BA.AUTHOR_NAME, BA.CATEGORY -- AUTHOR_NAME 추가
ORDER BY BA.AUTHOR_ID ASC, BA.CATEGORY DESC;
