WITH USER_LIST AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
)
SELECT
    USER_ID,
    NICKNAME,
    -- Nullable한 STREET_ADDRESS2에 대한 별도 처리 필요
    -- NULL일때의 마지막 공백을 처리하기 위해 전체 CONCAT을 TRIM()으로 감싸기
    TRIM(CONCAT(TRIM(CITY), ' ', TRIM(STREET_ADDRESS1), ' ', IFNULL(TRIM(STREET_ADDRESS2), ''))) AS '전체주소',
    CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER
WHERE USER_ID IN (SELECT WRITER_ID FROM USER_LIST)
ORDER BY USER_ID DESC;