WITH HIGHEST AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
SELECT
    CONCAT('/home/grep/src/', UF.BOARD_ID, '/', UF.FILE_ID, UF.FILE_NAME, UF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE UF JOIN HIGHEST H
    ON UF.BOARD_ID = H.BOARD_ID
ORDER BY UF.FILE_ID DESC;
