WITH LIVE_APPOINT AS (
    SELECT A.APNT_NO, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
    FROM DOCTOR D
    JOIN APPOINTMENT A ON D.DR_ID = A.MDDR_ID
    WHERE A.APNT_CNCL_YN = 'N'
      AND A.MCDP_CD = 'CS'
      AND A.APNT_YMD >= '2022-04-13'
      AND A.APNT_YMD < '2022-04-14'
)
SELECT LA.APNT_NO, P.PT_NAME, LA.PT_NO,
       LA.MCDP_CD, LA.DR_NAME, LA.APNT_YMD
FROM LIVE_APPOINT LA
JOIN PATIENT P ON LA.PT_NO = P.PT_NO
ORDER BY LA.APNT_YMD ASC;